name: Build Pages for CDN

on:
  workflow_dispatch: {}

permissions: {}

jobs:
  get-releases:
    name: Get releases
    outputs:
      tags: ${{ steps.get-tags.outputs.tags }}
    runs-on: ubuntu-latest

    steps:
      - env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release list \
            --json createdAt,isDraft,isLatest,isPrerelease,name,publishedAt,tagName \
            --limit 1000 \
            --repo microsoft/botframework-webchat \
            | jq -r '.' \
            | tee releases.json

      - uses: actions/upload-artifact@v6
        with:
          name: releases
          path: releases.json

      - id: get-tags
        run: |
          echo tags=$(cat releases.json | jq -c 'map({ tag: (.tagName | sub("^v"; "")) })') \
                | tee --append $GITHUB_OUTPUT

  download-release:
    continue-on-error: true
    needs:
      - get-releases
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include: ${{ fromJSON(needs.get-releases.outputs.tags) }}

    steps:
      - env:
          GH_TOKEN: ${{ github.token }}
        name: Download tarball
        run: |
          gh release download \
            v${{ matrix.tag }} \
            --pattern botframework-webchat-${{ matrix.tag }}.tgz \
            --repo microsoft/botframework-webchat

      - name: List tarball content
        run: tar -tf $(ls -1 *.tgz)

      - name: Extract tarball
        run: |
          mkdir -p dist/${{ matrix.tag }}/

          tar \
            -xzf $(ls -1 *.tgz) \
            --directory=dist/${{ matrix.tag }}/ \
            --exclude=stats.json \
            --strip-components=2 \
            --wildcards \
            package/dist/**

          ls -laR

      - name: Upload artifact
        uses: actions/upload-artifact@v6
        with:
          name: dist-${{ matrix.tag }}
          path: dist/**
