name: Build Pages for CDN

on:
  workflow_dispatch: {}

permissions: {}

jobs:
  get-releases:
    name: Get releases
    outputs:
      tags: ${{ steps.get-tags.outputs.tags }}
    runs-on: ubuntu-latest

    steps:
      - env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release list \
            --json createdAt,isDraft,isLatest,isPrerelease,name,publishedAt,tagName \
            --limit 1000 \
            --repo microsoft/botframework-webchat \
            | jq -r '.' \
            | tee releases.json

      - uses: actions/upload-artifact@v6
        with:
          name: releases
          path: releases.json

      - id: get-tags
        run: |
          echo tags=$(cat releases.json | jq -c '
            map({
              tag: (.tagName | sub("^v"; ""))
            })') | tee --append $GITHUB_OUTPUT

  download:
    continue-on-error: true
    name: Download bundles
    needs:
      - get-releases
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include: ${{ fromJSON(needs.get-releases.outputs.tags) }}

    steps:
      - env:
          GH_TOKEN: ${{ github.token }}
        name: View release
        run: gh release view v${{ matrix.tag }} --repo microsoft/botframework-webchat

      - name: Create directory
        run: mkdir -p dist/${{ matrix.tag }}/

      - env:
          GH_TOKEN: ${{ github.token }}
        name: Download tarball
        run: |
          gh release download \
            v${{ matrix.tag }} \
            --dir dist/${{ matrix.tag }} \
            --pattern *.js \
            --pattern *.js.map \
            --pattern *.js*.txt \
            --repo microsoft/botframework-webchat

      - name: List files
        run: ls -laR dist/

      - name: Upload artifact
        uses: actions/upload-artifact@v6
        with:
          name: dist-${{ matrix.tag }}
          path: dist/**
