name: ðŸš€ Build Pages for CDN

on:
  workflow_dispatch: {}

permissions: {}

jobs:
  get-releases:
    name: Get releases
    outputs:
      tags: ${{ steps.get-tags.outputs.tags }}
    runs-on: ubuntu-latest

    steps:
      - env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release list \
            --json createdAt,isDraft,isLatest,isPrerelease,name,publishedAt,tagName \
            --limit 1000 \
            --repo microsoft/botframework-webchat \
            | jq -r '.' \
            | tee releases.json

      - uses: actions/upload-artifact@v6
        with:
          name: releases
          path: releases.json

      - id: get-tags
        run: |
          echo tags=$(cat releases.json | jq -c '
            map({
              tag: (.tagName | sub("^v"; ""))
            })') | tee --append $GITHUB_OUTPUT

  download-bundle:
    continue-on-error: true
    name: Download bundles
    needs:
      - get-releases
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include: ${{ fromJSON(needs.get-releases.outputs.tags) }}

    steps:
      - uses: actions/setup-node@v6
        with:
          node-version: 24

      - id: check-eligibility
        name: Check version eligibility
        run: |
          echo Only versions \> 0.10.* are supported on CDN.

          version=${{ matrix.tag }}

          set +e
          npx semver $version --range \>0.10

          echo eligible=$([[ $? -eq 0 ]] && echo true || echo false) | tee --append $GITHUB_OUTPUT

      - if: steps.check-eligibility.outputs.eligible == 'true'
        name: Create directory
        run: mkdir -p dist/${{ matrix.tag }}/

      - env:
          GH_TOKEN: ${{ github.token }}
        if: steps.check-eligibility.outputs.eligible == 'true'
        name: Download tarball
        run: |
          gh release download \
            v${{ matrix.tag }} \
            --dir dist/${{ matrix.tag }} \
            --pattern *.js \
            --pattern *.js.map \
            --pattern *.js*.txt \
            --repo microsoft/botframework-webchat

      - if: steps.check-eligibility.outputs.eligible == 'true'
        name: List files
        run: ls -laR dist/

      - if: steps.check-eligibility.outputs.eligible == 'true'
        name: Upload artifact
        uses: actions/upload-artifact@v6
        with:
          name: dist-${{ matrix.tag }}
          path: dist/**

  merge-artifact:
    name: Merge artifacts
    needs:
      - download-bundle
    runs-on: ubuntu-latest

    steps:
      - uses: actions/upload-artifact/merge@v4
        with:
          name: dist
          pattern: dist-*
          delete-merged: true

  create-pull-request:
    environment:
      name: pull-request
      url: ${{ steps.create-pull-request.outputs.url }}
    name: Create pull request
    needs:
      - merge-artifact
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
        with:
          path: repo
          ref: gh-pages

      - id: setup-repository
        name: Setup repository
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          BRANCH_NAME="update-gh-pages-$(date +%Y%m%d-%H%M%S)"

          git checkout -b "$BRANCH_NAME"

          echo branch-name=$BRANCH_NAME | tee --append $GITHUB_OUTPUT
        working-directory: repo/

      - uses: actions/download-artifact@v6
        with:
          name: dist
          path: artifact

      - name: Copy bundles to botframework-webchat@x.y.z
        run: |
          find -mindepth 1 -maxdepth 1 -type d | while read dir; do
            version=$(basename "$dir")

            target="${{ github.workspace }}/repo/botframework-webchat@$version"

            mkdir -p $target
            cp -r $dir/* $target
          done
        working-directory: artifact

      - name: Copy bundles to botframework-webchat/x.y.z
        run: |
          find -mindepth 1 -maxdepth 1 -type d | while read dir; do
            version=$(basename "$dir")

            target="${{ github.workspace }}/repo/botframework-webchat/$version"

            mkdir -p $target
            cp -r $dir/* $target
          done
        working-directory: artifact

      - name: List repository content
        run: ls -laR
        working-directory: repo/

      - env:
          GH_TOKEN: ${{ github.token }}
        id: create-pull-request
        name: Create pull request
        run: |
          BRANCH_NAME=${{ steps.setup-repository.outputs.branch-name }}

          touch .nojekyll

          git add .

          if git diff --staged --quiet; then
            echo "No changes to commit."
            exit 0
          fi

          git commit -m "Update CDN files from microsoft/botframework-webchat"

          # Push the branch
          git push origin "$BRANCH_NAME"

          echo url=$(gh pr create \
            --base gh-pages \
            --head "$BRANCH_NAME" \
            --title "Update CDN files" \
            --body "This PR updates the CDN files from microsoft/botframework-webchat.

          Workflow run: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}.") | tee --append $GITHUB_OUTPUT
        working-directory: repo/
